<?php

$country_list = [
    'Belgique',
    'France',
    'Suisse',
    'Afghanistan',
    'Îles Åland',
    'Albanie',
    'Algérie',
    'Samoa américaines',
    'Andorre',
    'Angola',
    'Anguilla',
    'Antarctique',
    'Antigua-et-Barbuda',
    'Argentine',
    'Arménie',
    'Aruba',
    'Australie',
    'Autriche',
    'Azerbaïdjan',
    'Bahamas',
    'Bahreïn',
    'Bangladesh',
    'Barbade',
    'Biélorussie',
    'Belize',
    'Bénin',
    'Bermudes',
    'Bhoutan',
    'Bolivie',
    'Bosnie-Herzégovine',
    'Botswana',
    'Île Bouvet',
    'Brésil',
    'Territoire britannique de l’océan Indien',
    'Brunei',
    'Bulgarie',
    'Burkina Faso',
    'Burundi',
    'Cap-Vert',
    'Cambodge',
    'Cameroun',
    'Canada',
    'Pays-Bas caribéens',
    'Îles Caïmans',
    'République centrafricaine',
    'Tchad',
    'Chili',
    'Chine',
    'Île Christmas',
    'Îles Cocos',
    'Colombie',
    'Comores',
    'Congo-Brazzaville',
    'Congo-Kinshasa',
    'Îles Cook',
    'Costa Rica',
    'Croatie',
    'Cuba',
    'Curaçao',
    'Chypre',
    'Tchéquie',
    'Côte d’Ivoire',
    'Danemark',
    'Djibouti',
    'Dominique',
    'République dominicaine',
    'Équateur',
    'Égypte',
    'Salvador',
    'Guinée équatoriale',
    'Érythrée',
    'Estonie',
    'Eswatini',
    'Éthiopie',
    'Îles Malouines (Îles Falkland)',
    'Îles Féroé',
    'Fidji',
    'Finlande',
    'Guyane française',
    'Polynésie française',
    'Terres australes françaises',
    'Gabon',
    'Gambie',
    'Géorgie',
    'Allemagne',
    'Ghana',
    'Gibraltar',
    'Grèce',
    'Groenland',
    'Grenade',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernesey',
    'Guinée',
    'Guinée-Bissau',
    'Guyana',
    'Haïti',
    'Îles Heard-et-MacDonald',
    'Honduras',
    'Hong Kong',
    'Hongrie',
    'Islande',
    'Inde',
    'Indonésie',
    'Iran',
    'Irak',
    'Irlande',
    'Île de Man',
    'Israël',
    'Italie',
    'Jamaïque',
    'Japon',
    'Jersey',
    'Jordanie',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Corée du Nord',
    'Corée du Sud',
    'Kosovo',
    'Koweït',
    'Kirghizstan',
    'Laos',
    'Lettonie',
    'Liban',
    'Lesotho',
    'Liberia',
    'Libye',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Macao',
    'Macédoine du Nord',
    'Madagascar',
    'Malawi',
    'Malaisie',
    'Maldives',
    'Mali',
    'Malte',
    'Îles Marshall',
    'Martinique',
    'Mauritanie',
    'Maurice',
    'Mayotte',
    'Mexique',
    'Micronésie',
    'Moldavie',
    'Monaco',
    'Mongolie',
    'Monténégro',
    'Montserrat',
    'Maroc',
    'Mozambique',
    'Myanmar (Birmanie)',
    'Namibie',
    'Nauru',
    'Népal',
    'Pays-Bas',
    'Nouvelle-Calédonie',
    'Nouvelle-Zélande',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Île Norfolk',
    'Îles Mariannes du Nord',
    'Norvège',
    'Oman',
    'Pakistan',
    'Palaos',
    'Palestine',
    'Panama',
    'Papouasie-Nouvelle-Guinée',
    'Paraguay',
    'Pérou',
    'Philippines',
    'Îles Pitcairn',
    'Pologne',
    'Portugal',
    'Porto Rico',
    'Qatar',
    'La Réunion',
    'Roumanie',
    'Russie',
    'Rwanda',
    'Saint-Barthélemy',
    'Sainte-Hélène',
    'Saint-Christophe-et-Niévès',
    'Sainte-Lucie',
    'Saint-Martin',
    'Saint-Pierre-et-Miquelon',
    'Saint-Vincent-et-les Grenadines',
    'Samoa',
    'Saint-Marin',
    'Sao Tomé-et-Principe',
    'Arabie saoudite',
    'Sénégal',
    'Serbie',
    'Seychelles',
    'Sierra Leone',
    'Singapour',
    'Saint-Martin (partie néerlandaise)',
    'Slovaquie',
    'Slovénie',
    'Îles Salomon',
    'Somalie',
    'Afrique du Sud',
    'Géorgie du Sud-et-les Îles Sandwich du Sud',
    'Soudan du Sud',
    'Espagne',
    'Sri Lanka',
    'Soudan',
    'Suriname',
    'Svalbard et Jan Mayen',
    'Suède',
    'Syrie',
    'Taïwan',
    'Tadjikistan',
    'Tanzanie',
    'Thaïlande',
    'Timor oriental',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinité-et-Tobago',
    'Tunisie',
    'Turquie',
    'Turkménistan',
    'Îles Turques-et-Caïques',
    'Tuvalu',
    'Îles mineures éloignées des États-Unis',
    'Ouganda',
    'Ukraine',
    'Émirats arabes unis',
    'Royaume-Uni',
    'États-Unis',
    'Uruguay',
    'Ouzbékistan',
    'Vanuatu',
    'État de la Cité du Vatican',
    'Venezuela',
    'Viêt Nam',
    'Îles Vierges britanniques',
    'Îles Vierges des États-Unis',
    'Wallis-et-Futuna',
    'Sahara occidental',
    'Yémen',
    'Zambie',
    'Zimbabwe'
];

function createDropDown(array $country_array): string
{

    if (!is_array($country_array) || count($country_array) === 0) {
        return '<option>Invalid or empty country list provided.</option>';
    }

    $options = '';

    foreach ($country_array as $name) {
        $escaped_name = htmlspecialchars($name, ENT_QUOTES, 'UTF-8');
        $options .= "<option value='$escaped_name'>$escaped_name</option>";
    }

    return $options;
}